[project]
name = "monitor-mcp-server"
version = "0.1.0"
description = "monitor mcp server"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp[cli]>=1.6.0",
    "psutil>=5.9.0",
]
